version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      SPRING_PROFILE: prod
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - db_network

  db:
    image: "postgres:16.3-alpine3.19"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - db_network
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - db_network
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  db_network:
    driver: bridge

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
